version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg_data:
    driver: local
