version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Ajout d'un volume pour les fichiers de configuration ou scripts SQL, si nécessaire
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      # Montage du code du backend, ce qui permet d'éviter de redémarrer le conteneur
      - ./backend:/app  # Assure-toi que ce soit le bon répertoire pour ton code backend
      - ./backend/requirements.txt:/app/requirements.txt  # Si tu veux synchroniser tes dépendances directement

  frontend:
    build: ./frontend
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html  # Monte le dossier frontend local dans le conteneur
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # Monte le fichier de config nginx


volumes:
  pg_data:
    driver: local
