INSERT INTO public."Ingredients"(name)
	VALUES 
('Jambon'),('Fromage'),('Oeuf'),('Sel'), ('Poivre'), ('Paprika'), ('Cumin'), ('Curcuma'), ('Gingembre'), ('Cannelle'), ('Clou de girofle'), ('Muscade'), ('Safran'),
('Piment'), ('Vanille'), ('Anis'), ('Badiane'), ('Cardamome'), ('Coriandre'), ('Fenouil'), ('Laurier'), ('Menthe'), ('Origan'),
('Persil'), ('Romarin'), ('Sauge'), ('Thym'), ('Basilic'), ('Ciboulette'), ('Estragon'), ('Aneth'), ('Cerfeuil'), ('Marjolaine'),
('Sarriette'), ('Livèche'), ('Hysope'), ('Mélisse'), ('Verveine'), ('Estragon de Russie'),('Saumon'), ('Thon'), ('Truite'), ('Crevette'), ('Crabe'), ('Homard'), ('Moule'), ('Huître'), ('Calamar'), ('Seiche'),
('Sole'), ('Cabillaud'), ('Merlan'), ('Sardine'), ('Anchois'), ('Hareng'), ('Maquereau'), ('Bar'), ('Dorade'), ('Lotte'),
('Raie'), ('Saint-Jacques'), ('Langouste'), ('Langoustine'), ('Gambas'), ('Palourde'), ('Coquille Saint-Jacques'), ('Escargot'), ('Grenouille'), ('Anguille'),
('Barbue'), ('Carpe'), ('Colin'), ('Dorade royale'), ('Églefin'), ('Flétan'), ('Grondin'), ('Haddock'), ('Lieu'), ('Loup de mer'),
('Morue'), ('Mulet'), ('Perche'), ('Plie'), ('Rouget'), ('Sole commune'), ('Turbot'), ('Vivaneau'), ('Dorade coryphène'), ('Espadon'),
('Marlin'), ('Requin'), ('Roussette'), ('Sabre'), ('Sériole'), ('Thazard'), ('Thon rouge'), ('Thon blanc'),('Poulet'), ('Bœuf'), ('Porc'), ('Agneau'), ('Canard'), ('Dinde'), ('Veau'), ('Lapin'), ('Chevreuil'), ('Sanglier'),
('Cerf'), ('Biche'), ('Lièvre'), ('Pigeon'), ('Perdrix'), ('Faisan'), ('Caille'), ('Autruche'), ('Kangourou'), ('Bison'),
('Cheval'), ('Chèvre'), ('Mouton'), ('Bœuf Wagyu'), ('Bœuf Angus'), ('Bœuf Charolais'), ('Bœuf Limousin'), ('Bœuf Salers'), ('Bœuf Aubrac'), ('Bœuf Hereford'),
('Bœuf Simmental'), ('Bœuf Blonde dAquitaine'), ('Bœuf Gascon'), ('Bœuf Normand'), ('Bœuf Parthenaise'),('Tomate'), ('Oignon'), ('Ail') , ('Poivron'), ('Champignon'), ('Courgette'), ('Carotte'), ('Pomme de terre'), ('Épinard'),
('Laitue'), ('Brocoli'), ('Chou-fleur'), ('Concombre'), ('Radis'), ('Betterave'), ('Navet'), ('Poireau'), ('Céleri'),
('Artichaut'), ('Asperge'), ('Aubergine'), ('Chou'), ('Chou de Bruxelles'), ('Chou frisé'), ('Échalote'), ('Endive'), ('Haricot vert'), ('Lentille'),
('Maïs'), ('Pois'), ('Pois chiche'), ('Poivron rouge'), ('Poivron vert'), ('Poivron jaune'), ('Potiron'), ('Rutabaga'), ('Soja'), ('Topinambour'),
('Truffe'), ('Yam'), ('Zucchini'), ('Cresson'), ('Céleri-rave'), ('Chou-rave'), ('Chou chinois'), ('Chou kale'), ('Chou pak choï'), ('Chou romanesco'),
('Chou rouge'), ('Chou blanc'), ('Chou vert'), ('Chou pointu'), ('Chou palmier'), ('Chou de Milan'), ('Chou de Savoie'), ('Chou de Toscane'), ('Chou de Pékin'),('Abricot'), ('Ananas'), ('Banane'), ('Cerise'), ('Citron'), ('Clémentine'), ('Fraise'), ('Framboise'), ('Grenade'), ('Kiwi'),
('Mandarine'), ('Mangue'), ('Melon'), ('Mûre'), ('Myrtille'), ('Nectarine'), ('Orange'), ('Pamplemousse'), ('Papaye'), ('Pastèque'),
('Pêche'), ('Poire'), ('Pomme'), ('Prune'), ('Raisin'), ('Abricot sec'), ('Amande'), ('Cacahuète'), ('Châtaigne'), ('Datte'),
('Figue'), ('Noisette'), ('Noix'), ('Pistache'), ('Pruneau'), ('Raisin sec'), ('Avocat'), ('Cassis'), ('Coing'), ('Goyave'),
('Kaki'), ('Litchi'), ('Mirabelle'), ('Nashi'), ('Olive'), ('Pamplemousse rose'), ('Passion'), ('Pêche de vigne'), ('Pomme Granny Smith'), ('Pomme Golden'),
('Pomme Pink Lady'), ('Pomme Reinette'), ('Pomme Rouge'), ('Pomme Verte'), ('Quetsche'), ('Raisin blanc'), ('Raisin noir'), ('Raisin rouge'), ('Raisin sec blond'), ('Raisin sec noir');